title: "FoundByMe"
description: "FoundByMe Documentation"
#remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

url: "https://kimhabin2.github.io"  # 사용자 깃허브 주소
baseurl: "/foundbyme-custom"

color_scheme: light

