title: "FoundByMe"
description: "FoundByMe Documentation"
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

url: "https://KNaeon.github.io"  # 사용자 깃허브 주소
baseurl: "/foundbyme"

color_scheme: light

